"""Add profile and AI match fields

Revision ID: 0cb29f7e3b12
Revises: 3c5e515f4928
Create Date: 2026-08-17 15:42:47.946684

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cb29f7e3b12"
down_revision: str | Sequence[str] | None = "3c5e515f4928"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id = 1", name="profile_is_one_row"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("applications", sa.Column("job_ad", sa.Text(), nullable=True))
    op.add_column("applications", sa.Column("match_rating", sa.REAL(), nullable=True))
    op.add_column("applications", sa.Column("match_summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "match_summary")
    op.drop_column("applications", "match_rating")
    op.drop_column("applications", "job_ad")
    op.drop_table("profile")
    # ### end Alembic commands ###
