"""Add match strengths and weaknesses

Revision ID: 696386eef464
Revises: 0cb29f7e3b12
Create Date: 2026-08-17 20:44:42.924419

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "696386eef464"
down_revision: str | Sequence[str] | None = "0cb29f7e3b12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("match_strengths", sa.ARRAY(sa.Text()), nullable=True))
    op.add_column("applications", sa.Column("match_weaknesses", sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "match_weaknesses")
    op.drop_column("applications", "match_strengths")
    # ### end Alembic commands ###
