/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_applications__application_id__get"];
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_applications__application_id__delete"];
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["update_application_applications__application_id__patch"];
        trace?: never;
    };
    "/applications/{application_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score Match
         * @description Re-scores a stored advert against the current profile, which is the point of storing it.
         */
        post: operations["score_match_applications__application_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/status-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Status Update */
        post: operations["add_status_update_applications__application_id__status_updates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/status-updates/{update_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Status Update */
        delete: operations["delete_status_update_applications__application_id__status_updates__update_id__delete"];
        options?: never;
        head?: never;
        /** Update Status Update */
        patch: operations["update_status_update_applications__application_id__status_updates__update_id__patch"];
        trace?: never;
    };
    "/job-ads/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse Job Ad
         * @description Reads an advert. Stores nothing - the result is prefill, and the user has not agreed to it.
         */
        post: operations["analyse_job_ad_job_ads_analyse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_profile_get"];
        /** Replace Profile */
        put: operations["replace_profile_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Sector */
            sector: string;
            /** Location */
            location: string;
            /** Rating */
            rating?: number | null;
            /** Comment */
            comment?: string | null;
            /** Link */
            link?: string | null;
            first_update: components["schemas"]["StatusUpdateCreate"];
            /** Job Ad */
            job_ad?: string | null;
            /** Match Rating */
            match_rating?: number | null;
            /** Match Summary */
            match_summary?: string | null;
        };
        /** ApplicationDetail */
        ApplicationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Sector */
            sector: string;
            /** Location */
            location: string;
            /** Rating */
            rating: number | null;
            /** Comment */
            comment: string | null;
            /** Link */
            link: string | null;
            /** Job Ad */
            job_ad: string | null;
            /** Match Rating */
            match_rating: number | null;
            /** Match Summary */
            match_summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            current_status: components["schemas"]["Status"];
            /**
             * Last Update Date
             * Format: date
             */
            last_update_date: string;
            /** Updates */
            updates: components["schemas"]["StatusUpdateRead"][];
        };
        /** ApplicationListItem */
        ApplicationListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Sector */
            sector: string;
            /** Location */
            location: string;
            /** Rating */
            rating: number | null;
            /** Match Rating */
            match_rating: number | null;
            current_status: components["schemas"]["Status"];
            /**
             * Last Update Date
             * Format: date
             */
            last_update_date: string;
        };
        /** ApplicationPatch */
        ApplicationPatch: {
            /** Title */
            title?: string | null;
            /** Company */
            company?: string | null;
            /** Sector */
            sector?: string | null;
            /** Location */
            location?: string | null;
            /** Rating */
            rating?: number | null;
            /** Comment */
            comment?: string | null;
            /** Link */
            link?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobAdText */
        JobAdText: {
            /** Text */
            text: string;
        };
        /**
         * JobAnalysis
         * @description What one model call returns. Also the response body of POST /job-ads/analyse.
         *
         *     The match fields are null when there is no profile to score against. No defaults: OpenAI's
         *     strict structured outputs require every property to be required, and nullability is how
         *     "absent" is expressed.
         */
        JobAnalysis: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Sector */
            sector: string;
            /** Location */
            location: string;
            /** Match Rating */
            match_rating: number | null;
            /** Match Summary */
            match_summary: string | null;
        };
        /** ProfileRead */
        ProfileRead: {
            /** Content */
            content: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** ProfileWrite */
        ProfileWrite: {
            /** Content */
            content: string;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "Contacted" | "Applied" | "Interview" | "Offer" | "Rejected" | "Withdrawn";
        /** StatusUpdateCreate */
        StatusUpdateCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            status: components["schemas"]["Status"];
            /** Note */
            note?: string | null;
        };
        /** StatusUpdatePatch */
        StatusUpdatePatch: {
            /** Date */
            date?: string | null;
            status?: components["schemas"]["Status"] | null;
            /** Note */
            note?: string | null;
        };
        /** StatusUpdateRead */
        StatusUpdateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            status: components["schemas"]["Status"];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_applications_applications_get: {
        parameters: {
            query?: {
                include_closed?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_applications_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_match_applications__application_id__match_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_status_update_applications__application_id__status_updates_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_status_update_applications__application_id__status_updates__update_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                application_id: string;
                update_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_update_applications__application_id__status_updates__update_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                application_id: string;
                update_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdatePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_job_ad_job_ads_analyse_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobAdText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_profile_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_profile_profile_put: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
